End turn visibility
redweeka/Redweekraces pull request #20
Opened 2022-09-09 16:12 UTC by EdenDuman

2022-09-10 22:04 UTC, redweeka requested changes

2022-09-10 22:04 UTC, redweeka commented on app/src/main/java/com/example/redweekraces/utilities/Constants.java
> +        }
get it out of IslandMapConstants

and call the variables
public static final int MAX_DELAY_SECONDS_BETWEEN_TURNS = 6;
public static final int MIN_DELAY_SECONDS_BETWEEN_TURNS = 2;

2022-09-10 22:09 UTC, EdenDuman commented on app/src/main/java/com/example/redweekraces/models/map/MapGenerator.java
> +import static com.example.redweekraces.models.tiles.TilesFactory.BEACH_TILE;
זה תהליך אוטומטי של אופטימיזציה לאימפורטים

2022-09-12 14:47 UTC, redweeka commented on app/src/main/java/com/example/redweekraces/models/map/MapGenerator.java
> +import static com.example.redweekraces.models.tiles.TilesFactory.BEACH_TILE;
so don't do it

2022-09-12 14:50 UTC, redweeka requested changes

2022-09-12 14:50 UTC, redweeka commented on app/src/main/java/com/example/redweekraces/views/IslandRacesActivity.java
> +        }
add a comment

2022-09-14 17:19 UTC, EdenDuman commented on app/src/main/java/com/example/redweekraces/views/IslandRacesActivity.java
> +        this.stepsFinishedReminder.setVisibility(View.VISIBLE);
לשנות למה?
ומה הבעיה עם מה שקיים?

2022-09-14 21:00 UTC, redweeka commented on app/src/main/java/com/example/redweekraces/views/IslandRacesActivity.java
> +        this.stepsFinishedReminder.setVisibility(View.VISIBLE);
לשנות ל"לילה טוב, התור נגמר"
באנגלית "good night, turn over"

כי אנחנו כבר לא מתעסקים ברק צעדים, זה כבר תחילת וסיום תור

2022-09-14 21:07 UTC, redweeka requested changes
שנה את הטקסט ואני אכניס

2022-09-14 21:07 UTC, redweeka commented on app/src/main/java/com/example/redweekraces/views/IslandRacesActivity.java
> +        //  This is need to by by logic and not randomly
By by hahaha

2022-09-14 21:08 UTC, EdenDuman commented on app/src/main/java/com/example/redweekraces/views/IslandRacesActivity.java
> +        //  This is need to by by logic and not randomly
need to be*

2022-09-14 21:15 UTC, redweeka requested changes

2022-09-14 21:15 UTC, redweeka commented on app/src/main/java/com/example/redweekraces/views/IslandRacesActivity.java
> +        this.utils = new Utils();
Dont use utils like that
Should be static

2022-09-15 21:59 UTC, redweeka approved these changes

2022-09-15 21:59 UTC, merged