Random generator
redweeka/Redweekraces pull request #29
Opened 2022-10-25 19:34 UTC by redweeka

2022-10-29 19:51 UTC, EdenDuman requested changes

2022-10-29 19:51 UTC, EdenDuman commented on app/src/test/java/com/example/redweekraces/utilities/UtilsTest.java
>  public class UtilsTest {
rename to `RandomGeneratorTest`

2022-10-29 19:51 UTC, EdenDuman commented on app/src/main/java/com/example/redweekraces/views/RandomGeneratorActivity.java
> +        int isSucceedColor;
rename to something like `resultColor`

2022-10-29 19:51 UTC, EdenDuman commented on app/src/main/java/com/example/redweekraces/views/RandomGeneratorActivity.java
> +    Button succeed50Percent;
public?

2022-10-29 19:51 UTC, EdenDuman commented on app/src/main/java/com/example/redweekraces/utilities/RandomGenerator.java
> +    public static boolean isSucceedOn50percent() {
create only 1 function that get the percent to win
(It is better that it receives a variable of type double)

2022-10-29 19:51 UTC, EdenDuman commented on app/src/main/java/com/example/redweekraces/utilities/RandomGenerator.java
> +    public static boolean isSucceedOn75percent() {
create only 1 function that get the percent to win

2022-10-29 19:51 UTC, EdenDuman commented on app/src/main/java/com/example/redweekraces/utilities/RandomGenerator.java
> +    public static boolean isSucceedOn75percent() {
create only 1 function that get the percent to win
(It is better that it receives a variable of type double)

2022-10-29 19:59 UTC, EdenDuman commented on app/src/main/java/com/example/redweekraces/utilities/RandomGenerator.java
> +        // return new Random().nextInt(MAX_DELAY_SECONDS_BETWEEN_TURNS - MIN_DELAY_SECONDS_BETWEEN_TURNS + 1) + MIN_DELAY_SECONDS_BETWEEN_TURNS;
קוד לא אמור להיות בהערה

2022-10-30 20:38 UTC, redweeka commented on app/src/main/java/com/example/redweekraces/utilities/RandomGenerator.java
> +    public static boolean isSucceedOn50percent() {
אני אוהב שזה כתוב ככה. לדעתי זה יותר קריא וברור. זה המקום היחיד שבסדר לי שאין REUSE

2022-10-30 20:38 UTC, redweeka commented on app/src/main/java/com/example/redweekraces/utilities/RandomGenerator.java
> +    public static boolean isSucceedOn75percent() {
זו הערה כפולה

2022-10-30 20:38 UTC, redweeka commented on app/src/main/java/com/example/redweekraces/utilities/RandomGenerator.java
> +    public static boolean isSucceedOn75percent() {
ממש התעצבנת על זה אה..

2022-10-30 20:38 UTC, redweeka commented on app/src/main/java/com/example/redweekraces/views/RandomGeneratorActivity.java
> +    Button succeed50Percent;
צודק זה צריך להיות PRIVATE

2022-10-30 20:38 UTC, redweeka commented on app/src/main/java/com/example/redweekraces/views/RandomGeneratorActivity.java
> +        int isSucceedColor;
מה הבעיה בשם הזה? (הוא מסביר את עצמו - צבע של האם הצליח!)

2022-10-30 20:38 UTC, redweeka commented on app/src/test/java/com/example/redweekraces/utilities/UtilsTest.java
>  public class UtilsTest {
סבבה

2022-11-05 14:34 UTC, EdenDuman commented on app/src/main/java/com/example/redweekraces/views/RandomGeneratorActivity.java
> +        int isSucceedColor;
כי במקרה שאם הוא לא צליח אז המשמעות שלו לא נכונה
וגם משתנים שמתחילים ב IS הכוונה לבוליאנים

2022-11-07 07:59 UTC, redweeka commented on app/src/main/java/com/example/redweekraces/views/RandomGeneratorActivity.java
> +        int isSucceedColor;
צודק שis זה לבוליאנים
אשנה לresultColor

2022-11-18 12:15 UTC, EdenDuman approved these changes

2022-11-18 12:27 UTC, merged